services:
  db:
   image: pgvector/pgvector:pg16-trixie
   restart: always
   shm_size: 128mb
   environment:
     POSTGRES_PASSWORD: 123456abc
     POSTGRES_USER: cody
     POSTGRES_DB: pokeApi
   volumes:
     - ./sql:/docker-entrypoint-initdb.d
   ports:
     - 5432:5432
   command: ["postgres", "-c", "log_statement=all"] # Enables verbose logging
